### ISSUE TITLE
Docker compose doesn't work with mqtt

### ISSUE THREAD

**Issue by schollz** [schollz/find3#102]
The following configuration results in a tcp socket error for mqtt.

```
find3server:
  container_name: find3server
  restart: unless-stopped
  image: schollz/find3
  environment:
    - MQTT_ADMIN=admin
    - MQTT_PASS=mypass
    - MQTT_SERVER='localhost:1883'
  volumes:
    - /home/USER/find3server:/data
  ports:
    - "11883:1883"
    - "8003:8003"
```
